name: VisantaraDungeonV2
version: '1.0-SNAPSHOT'
main: my.pikrew.visantaraDungeonV2.VisantaraDungeonV2
api-version: '1.21'
author: Pikrew
description: Advanced dungeon system with hologram entrance

commands:
  vdungeon:
    description: Main VDungeon command
    usage: /vdungeon <create|delete|play|exit|list|hologram|setspawn>
    aliases: [vd, dungeon]

  editmenu:
    description: Open player visibility settings menu
    usage: /editmenu
    aliases: [em, settings]

  party:
    description: Party management command
    usage: /party <create|invite|accept|decline|leave|kick|view|disband>
    aliases: [p]

  dungeonreset:
    description: Reset player's dungeon lives
    usage: /dungeonreset <player>
    permission: dungeonchances.reset
    permission-message: "You don't have permission to use this command!"

  dungeonreload:
    description: Reload plugin configuration
    usage: /dungeonreload
    permission: dungeonchances.reload
    permission-message: "You don't have permission to use this command!"

permissions:
  vdungeon.*:
    description: Gives access to all VDungeon commands
    default: op
    children:
      vdungeon.create: true
      vdungeon.delete: true
      vdungeon.play: true
      vdungeon.exit: true
      vdungeon.list: true
      vdungeon.setspawn: true
      vdungeon.hologram.*: true

  vdungeon.create:
    description: Allows creating dungeons
    default: op

  vdungeon.delete:
    description: Allows deleting dungeons
    default: op

  vdungeon.play:
    description: Allows entering dungeons
    default: true

  vdungeon.exit:
    description: Allows exiting dungeons
    default: true

  vdungeon.list:
    description: Allows listing dungeons
    default: true

  vdungeon.setspawn:
    description: Allows setting dungeon spawn
    default: op

  vdungeon.hologram.*:
    description: Gives access to all hologram commands
    default: op
    children:
      vdungeon.hologram.create: true
      vdungeon.hologram.delete: true
      vdungeon.hologram.list: true

  vdungeon.hologram.create:
    description: Allows creating holograms
    default: op

  vdungeon.hologram.delete:
    description: Allows deleting holograms
    default: op

  vdungeon.hologram.list:
    description: Allows listing holograms
    default: op

  editmenu.use:
    description: Allows using the edit menu
    default: true

  party.*:
    description: Gives access to all party commands
    default: true
    children:
      party.create: true
      party.invite: true
      party.accept: true
      party.decline: true
      party.leave: true
      party.kick: true
      party.view: true
      party.disband: true

  party.create:
    description: Allows creating a party
    default: true

  party.invite:
    description: Allows inviting players to party
    default: true

  party.accept:
    description: Allows accepting party invitations
    default: true

  party.decline:
    description: Allows declining party invitations
    default: true

  party.leave:
    description: Allows leaving a party
    default: true

  party.kick:
    description: Allows kicking members from party (leader only)
    default: true

  party.view:
    description: Allows viewing party members
    default: true

  party.disband:
    description: Allows disbanding a party (leader only)
    default: true

  dungeonchances.*:
    description: Gives all dungeon chances permissions
    default: op
    children:
      dungeonchances.reset: true
      dungeonchances.reload: true

  dungeonchances.reset:
    description: Allows resetting player's dungeon lives
    default: op

  dungeonchances.reload:
    description: Allows reloading plugin configuration
    default: op